version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000" # Expose port 8000
    env_file:
      - ./app/.env
    volumes:
      - .:/app
    # depends_on:
    # - db
# db placeholder
# db:

# volumes:
#   db_data:
