services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ansor
      POSTGRES_PASSWORD: "00005612"
      POSTGRES_DB: transaction_db
    ports:
      - 5436:5432
