services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: ansor
      POSTGRES_PASSWORD: "00005612"
      POSTGRES_DB: transaction_db
    ports:
      - 5436:5432
    healthcheck:
      test: pg_isready -d transaction_db -U ansor
      interval: 10s
      timeout: 5s
      retries: 5
